#!/bin/sh

# vars
datetime="todo"
logpath=".gitpsoft/logs"
branch=$(git branch | grep '*' | sed 's/* //') 
PS_PROJ_DB="$branch"
exec < /dev/tty
read -p "Import projects into DB '$branch'? " import
if [[ $import =~ ^[Nn]$ ]]; then
	exit
fi

if [ -z "$PS_PROJ_USER" ]; then
	read -p "DB user: " PS_PROJ_USER
fi
if [ -z "$PS_PROJ_PASS" ]; then
	read -s -p "DB password: " PS_PROJ_PASS
fi


# find project dirs
projs=($(find . -maxdepth 1 -type d | cut -c 3-))
# import projects into DB
for proj in ${projs[@]}
do
	logname="$proj-CHECKOUT-$datetime.log"
	cmd.exe /c "PSIDE.EXE -HIDE -PJFF $proj -FP . -CT ORACLE -CD $PS_PROJ_DB -CO $PS_PROJ_USER -CP $PS_PROJ_PASS -QUIT -LF $logpath/$logname"
done
